name: adguardhome

services:
  nfs:
    image: nfs-server
    build: 
      context: .
      dockerfile: Dockerfile.nfs
    container_name: nfs
    ports:
      - "2049:2049"
      - "20048:20048"
    volumes:
      - /mnt/nfs:/exports
    platform: linux/x86_64
  adguardhome:
    image: adguard/adguardhome
    network_mode: host
    volumes:
      - ./conf/AdGuardHome.yaml:/opt/adguardhome/conf/AdGuardHome.yaml 
      - /opt/adguardhome/work:/opt/adguardhome/work
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    ports:
      - 9100:9100
    restart: unless-stopped
    container_name: node-exporter
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 9101:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro