name: adguardhome

services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    ports:
      - 9100:9100
    restart: always
    container_name: node-exporter
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 9101:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
  vault_replica:
    image: hashicorp/vault
    container_name: vault-replica
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_UI: true
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./data/vault/logs:/vault/logs/:rw
      - ./data/vault/data:/vault/data/:rw
      - ./conf/vault.hcl:/vault/config/config.hcl:rw
      - ./data/vault/file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl