kind: Service
apiVersion: v1
metadata:
  name: adguard-http
  namespace: {{ .Values.namespace }}
spec:
  ipFamilies:
  - IPv4
  ports:
    - name: adguard-http 
      protocol: TCP 
      port: 8090       
spec:
  type: ExternalName
  externalName: 192.168.0.219