apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/demo
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: demo
          image: 'postgres:12.17'
          imagePullPolicy: Always
          name: db
          ports:
            - containerPort: 5432
              name: db
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: demo-nfs-pvc
      volumes:
        - name: demo-nfs-pvc
          persistentVolumeClaim:
            claimName: demo-nfs-pvc