apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ssh-backup
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backup-ssh-key
  data:
  - secretKey: id_rsa 
    remoteRef: 
      key: vault/backup-ssh-key
      property: id_rsa