name: hserver
namespace: hserver
helm-charts:
  name: hserver
  namespace: hserver
  namespaces:
    - name: hserver
  ingresses:
    - name: adguard-http
      commonName: adguard.tjth.co
      secretName: adguard-tjth-co
      port: 8090