name: hvm-access
namespace: hvm-access
helm-charts:
  name: hvm-access
  namespace: hvm-access
  namespaces:
    - name: hvm-access
  ingresses:
    - name: 192.168.0.218
      commonName: adguard.tjth.co
      secretName: adguard-tjth-co
      port: 8090