name: hserver
namespace: hserver
helm-charts:
  name: hserver
  namespace: hserver
  namespaces:
    - name: hserver

nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.0.219
    path: /mnt/nfs
  storageClass:
    onDelete: true
    defaultClass: true